import { obsidianProjectDocuments } from "./project-document-data";

export type CasePage = "overview" | "charter" | "risk" | "stakeholder";

export type KnowledgeTopic = {
  id: string;
  title: string;
  kind: "framework" | "management-area" | "process-group" | "process" | "artifact" | "tool";
  domain: string;
  processGroup?: string;
  definition: string;
  plainLanguage: string;
  timing: string;
  inputs: string[];
  tools: string[];
  outputs: string[];
  related: string[];
  source: string;
  sourceContent?: string;
  casePage: CasePage;
};

export const knowledgeTopics: KnowledgeTopic[] = [
  {
    id: "KB-LIFECYCLE",
    title: "项目生命周期",
    kind: "framework",
    domain: "项目运行环境",
    definition: "由促进交付节奏的项目阶段和产生项目交付物所需的开发方法组成。",
    plainLanguage: "它回答项目会经历哪些阶段、各阶段交付什么，以及采用怎样的开发方法推进。",
    timing: "从项目概念形成开始，持续到成果移交和项目结束。",
    inputs: ["组织战略", "商业需求", "项目特征"],
    tools: ["开发方法选择", "阶段门", "生命周期裁剪"],
    outputs: ["阶段结构", "交付节奏", "治理节点"],
    related: ["KB-PROCESS-GROUPS", "KB-CHARTER-PROCESS", "KB-CLOSE"],
    source: "《信息系统项目管理师教程（第4版）》· 项目生命周期",
    casePage: "overview",
  },
  {
    id: "KB-PROCESS-GROUPS",
    title: "五大过程组",
    kind: "framework",
    domain: "项目管理过程",
    definition: "将项目管理过程按管理目的组织为启动、规划、执行、监控和收尾五个过程组。",
    plainLanguage: "过程组不是项目阶段，而是会在不同阶段按需要反复介入的一组管理工作。",
    timing: "在整个项目生命周期中按阶段需要交叠开展。",
    inputs: ["项目阶段", "项目状态", "治理要求"],
    tools: ["过程裁剪", "滚动式规划", "阶段复盘"],
    outputs: ["管理活动组合", "阶段管理成果"],
    related: ["KB-PG-INIT", "KB-PG-PLAN", "KB-PG-EXEC", "KB-PG-MC", "KB-PG-CLOSE"],
    source: "《信息系统项目管理师教程（第4版）》· 项目管理过程组",
    casePage: "overview",
  },
  {
    id: "KB-PORTFOLIO",
    title: "项目组合",
    kind: "framework",
    domain: "项目管理层级",
    definition: "为了实现战略目标而组合在一起管理的项目、项目集、子项目组合和运营工作的集合。",
    plainLanguage: "把多个项目、项目集和运营工作放在组织战略与投资视角下统一选择、排序、分配资源和监督价值。",
    timing: "项目组合随组织战略持续存在，并在启动、规划、执行与优化阶段循环管理。",
    inputs: ["组织战略", "候选项目与项目集", "资源与投资约束"],
    tools: ["战略一致性分析", "优先级排序", "产能与能力管理"],
    outputs: ["项目组合路线图", "组件优先级", "资源分配决策"],
    related: ["KB-PROGRAM", "KB-ENTERPRISE-ENVIRONMENTAL-FACTORS"],
    source: "《信息系统项目管理师教程（第4版）》· 项目组合",
    casePage: "overview",
  },
  {
    id: "KB-PROGRAM",
    title: "项目集",
    kind: "framework",
    domain: "项目管理层级",
    definition: "经过协调管理以便获取单独管理这些项目时无法取得的收益和控制的一组相互关联的项目、子项目集和其他相关工作。",
    plainLanguage: "对一组相互关联的项目进行协调管理，重点获得单独管理各项目无法实现的整体效益与协同控制。",
    timing: "项目集从定义、交付到收尾进行全生命周期管理，并持续协调各组成项目的效益实现。",
    inputs: ["组织战略", "相关项目与工作", "预期效益"],
    tools: ["战略一致性管理", "效益管理", "项目集治理"],
    outputs: ["项目集路线图", "项目集管理计划", "整体效益"],
    related: ["KB-PORTFOLIO", "KB-LIFECYCLE"],
    source: "《信息系统项目管理师教程（第4版）》· 项目集",
    casePage: "overview",
  },
  {
    id: "KB-ENTERPRISE-ENVIRONMENTAL-FACTORS",
    title: "事业环境因素",
    kind: "framework",
    domain: "项目运行环境",
    definition: "项目团队不能直接控制、但会对项目产生影响、限制或指引作用的各种内外部条件。",
    plainLanguage: "它说明项目所处的现实环境，包括组织文化与结构、资源能力和可用性、设施分布、市场条件，以及行业法规和标准等。",
    timing: "在相关项目管理过程开始和开展时作为输入持续考虑，并随组织内外部环境变化重新评估。",
    inputs: ["组织内部环境", "组织外部环境", "市场与行业条件"],
    tools: ["环境分析", "组织能力评估", "市场条件分析"],
    outputs: ["项目约束与指引", "资源使用偏好", "管理决策依据"],
    related: ["KB-ORGANIZATIONAL-PROCESS-ASSETS", "KB-PROJECT-MANAGEMENT-PLAN"],
    source: "《信息系统项目管理师教程（第4版）》· 事业环境因素",
    sourceContent: "有助于识别对项目所需资源有特别兴趣或影响的那些干系人，以及影响资源使用偏好的干系人。\n\n能够影响规划资源管理过程的事业环境因素包括：\n1. 组织文化和结构；\n2. 设施和资源的物理分布；\n3. 现有资源的能力和可用性；\n4. 市场条件等。",
    casePage: "overview",
  },
  {
    id: "KB-ORGANIZATIONAL-PROCESS-ASSETS",
    title: "组织过程资产",
    kind: "framework",
    domain: "项目运行环境",
    definition: "执行组织所特有并使用的计划、过程、政策、程序和知识库，它们会影响项目的管理方式。",
    plainLanguage: "它把组织已经形成的制度、模板、历史信息和经验教训带入项目，并由项目执行和收尾继续补充更新。",
    timing: "在相关项目管理过程中作为输入使用，并在项目执行、监控和收尾时持续更新与沉淀。",
    inputs: ["组织政策与程序", "模板与指南", "历史信息与经验教训"],
    tools: ["过程裁剪", "模板复用", "知识管理"],
    outputs: ["项目管理依据", "组织知识复用", "组织过程资产更新"],
    related: ["KB-ENTERPRISE-ENVIRONMENTAL-FACTORS", "KB-PROJECT-MANAGEMENT-PLAN", "KB-CLOSE"],
    source: "《信息系统项目管理师教程（第4版）》· 组织过程资产",
    sourceContent: "能够影响规划资源管理过程的组织过程资产包括：\n1. 人力资源政策和程序；\n2. 物质资源管理政策和程序；\n3. 安全政策；\n4. 安保政策；\n5. 资源管理计划模板；\n6. 类似项目的历史信息等。\n\n结束收尾阶段的组织过程资产包括项目或阶段收尾指南或要求，以及配置管理知识库。",
    casePage: "overview",
  },
  {
    id: "KB-PG-INIT",
    title: "启动过程组",
    kind: "process-group",
    domain: "项目管理过程",
    definition: "包含制定项目章程和识别干系人，用于定义新项目或新阶段并取得正式授权。",
    plainLanguage: "确认为什么做、谁有权启动、谁会影响项目。每个新阶段开始时也可能再次介入。",
    timing: "项目开始和阶段开始时集中开展。",
    inputs: ["商业文件", "协议", "组织环境"],
    tools: ["专家判断", "数据收集", "会议"],
    outputs: ["项目章程", "干系人登记册", "假设日志"],
    related: ["KB-CHARTER-PROCESS", "KB-IDENTIFY-STAKEHOLDERS", "KB-PG-PLAN"],
    source: "《信息系统项目管理师教程（第4版）》· 启动过程组",
    casePage: "charter",
  },
  {
    id: "KB-PG-PLAN",
    title: "规划过程组",
    kind: "process-group",
    domain: "项目管理过程",
    definition: "明确项目范围、细化目标并制定实现目标所需行动方案的一组过程。",
    plainLanguage: "把章程里的高层级方向拆成可执行、可衡量、可控制的计划和基准。",
    timing: "组织准备阶段最集中，并随着信息增加滚动更新。",
    inputs: ["项目章程", "项目文件", "组织过程资产"],
    tools: ["分解", "估算", "分析", "规划会议"],
    outputs: ["项目管理计划", "各知识领域管理计划", "范围/进度/成本基准"],
    related: ["KB-PROJECT-MANAGEMENT-PLAN", "KB-IDENTIFY-RISKS", "KB-PG-EXEC"],
    source: "《信息系统项目管理师教程（第4版）》· 规划过程组",
    casePage: "overview",
  },
  {
    id: "KB-PG-EXEC",
    title: "执行过程组",
    kind: "process-group",
    domain: "项目管理过程",
    definition: "完成项目管理计划中确定的工作，以满足项目要求的一组过程。",
    plainLanguage: "组织团队和资源完成交付物，同时管理质量、沟通、知识、采购、风险应对和干系人参与。",
    timing: "系统建设和交付阶段最活跃。",
    inputs: ["项目管理计划", "项目文件", "批准的变更请求"],
    tools: ["领导力", "项目管理信息系统", "会议"],
    outputs: ["可交付成果", "工作绩效数据", "问题日志", "变更请求"],
    related: ["KB-PG-PLAN", "KB-PG-MC", "KB-STAKEHOLDER-REGISTER"],
    source: "《信息系统项目管理师教程（第4版）》· 执行过程组",
    casePage: "overview",
  },
  {
    id: "KB-PG-MC",
    title: "监控过程组",
    kind: "process-group",
    domain: "项目管理过程",
    definition: "跟踪、审查和调整项目进展与绩效，识别计划变更并启动相应变更的一组过程。",
    plainLanguage: "持续比较计划与实际，发现偏差，决定是否纠偏或正式变更。",
    timing: "贯穿大部分生命周期，在建设、验证和部署阶段持续介入。",
    inputs: ["项目管理计划", "项目文件", "工作绩效信息"],
    tools: ["数据分析", "挣值分析", "检查", "决策"],
    outputs: ["工作绩效报告", "变更请求", "计划和文件更新"],
    related: ["KB-INTEGRATED-CHANGE", "KB-RISK-REGISTER", "KB-PG-CLOSE"],
    source: "《信息系统项目管理师教程（第4版）》· 监控过程组",
    casePage: "risk",
  },
  {
    id: "KB-PG-CLOSE",
    title: "收尾过程组",
    kind: "process-group",
    domain: "项目管理过程",
    definition: "正式完成或结束项目、阶段或合同的一组过程。",
    plainLanguage: "确认成果被接受，完成移交、结算、归档和经验沉淀。",
    timing: "阶段结束、合同结束和项目最终结束时开展。",
    inputs: ["项目章程", "项目管理计划", "验收的可交付成果"],
    tools: ["文件分析", "回归分析", "会议"],
    outputs: ["最终成果移交", "最终报告", "组织过程资产更新"],
    related: ["KB-LIFECYCLE", "KB-PG-MC"],
    source: "《信息系统项目管理师教程（第4版）》· 收尾过程组",
    casePage: "overview",
  },
  {
    id: "KB-CHARTER-PROCESS",
    title: "制定项目章程",
    kind: "process",
    domain: "项目整合管理",
    processGroup: "启动过程组",
    definition: "编写一份正式批准项目并授权项目经理在项目活动中使用组织资源的文件的过程。",
    plainLanguage: "把项目从一个想法变成获得组织承诺和正式授权的工作。",
    timing: "仅开展一次，或在项目预定义点开展；应在详细规划之前完成。",
    inputs: ["商业文件", "协议", "事业环境因素", "组织过程资产"],
    tools: ["专家判断", "数据收集", "人际关系与团队技能", "会议"],
    outputs: ["项目章程", "假设日志"],
    related: ["KB-PROJECT-CHARTER", "KB-ASSUMPTION-LOG", "KB-IDENTIFY-STAKEHOLDERS"],
    source: "《信息系统项目管理师教程（第4版）》· 制定项目章程",
    casePage: "charter",
  },
  {
    id: "KB-PROJECT-CHARTER",
    title: "项目章程",
    kind: "artifact",
    domain: "项目整合管理",
    definition: "记录项目目的、目标、需求、范围边界、里程碑、风险、资源、审批要求和授权等高层级信息的正式文件。",
    plainLanguage: "它不是详细计划，而是项目存在的依据、边界和项目经理授权的凭证。",
    timing: "在启动阶段创建，批准后标志项目正式启动；修订需要发起人权限。",
    inputs: ["商业需求", "项目选择结果", "协议"],
    tools: ["章程模板", "访谈", "会议"],
    outputs: ["正式授权", "高层级范围与目标", "审批和退出标准"],
    related: ["KB-CHARTER-PROCESS", "KB-IDENTIFY-RISKS", "KB-IDENTIFY-STAKEHOLDERS"],
    source: "《信息系统项目管理师教程（第4版）》· 项目章程",
    casePage: "charter",
  },
  {
    id: "KB-ASSUMPTION-LOG",
    title: "假设日志",
    kind: "artifact",
    domain: "项目整合管理",
    definition: "记录项目生命周期中的全部假设条件和制约因素，并持续更新。",
    plainLanguage: "把暂时相信但尚未证实的事情单独保存，避免它们被误当成事实。",
    timing: "制定项目章程时首次形成，之后由多个管理过程持续更新。",
    inputs: ["访谈事实", "初始假设", "制约因素"],
    tools: ["假设分析", "制约因素分析"],
    outputs: ["可追踪的假设与制约条件"],
    related: ["KB-CHARTER-PROCESS", "KB-IDENTIFY-RISKS", "KB-RISK-REGISTER"],
    source: "《信息系统项目管理师教程（第4版）》· 假设日志",
    casePage: "charter",
  },
  {
    id: "KB-IDENTIFY-STAKEHOLDERS",
    title: "识别干系人",
    kind: "process",
    domain: "项目干系人管理",
    processGroup: "启动过程组",
    definition: "定期识别项目干系人，分析和记录其利益、参与度、相互依赖性、影响力和对项目成功潜在影响的过程。",
    plainLanguage: "找出谁能影响项目、谁会被项目影响，以及项目团队应该给予多少关注。",
    timing: "首次在章程编制和批准之前或同时开展，之后至少在每个阶段开始或发生重大变化时重复。",
    inputs: ["项目章程", "商业文件", "项目管理计划", "项目文件", "协议"],
    tools: ["问卷和调查", "头脑风暴", "干系人分析", "权力利益方格", "会议"],
    outputs: ["干系人登记册", "变更请求", "项目管理计划更新", "项目文件更新"],
    related: ["KB-STAKEHOLDER-REGISTER", "KB-POWER-INTEREST", "KB-ENGAGEMENT-MATRIX"],
    source: "《信息系统项目管理师教程（第4版）》· 识别干系人",
    casePage: "stakeholder",
  },
  {
    id: "KB-STAKEHOLDER-REGISTER",
    title: "干系人登记册",
    kind: "artifact",
    domain: "项目干系人管理",
    definition: "记录已识别干系人的基本信息、评估信息和分类信息的项目文件。",
    plainLanguage: "它把角色、诉求、权力、利益、态度和参与程度放在一张可维护的清单里。",
    timing: "识别干系人时首次创建，并在项目期间持续更新。",
    inputs: ["项目章程", "协议", "组织结构", "访谈信息"],
    tools: ["干系人分析", "数据收集", "数据表现"],
    outputs: ["基本信息", "评估信息", "分类信息"],
    related: ["KB-IDENTIFY-STAKEHOLDERS", "KB-POWER-INTEREST", "KB-ENGAGEMENT-MATRIX"],
    source: "《信息系统项目管理师教程（第4版）》· 干系人登记册",
    casePage: "stakeholder",
  },
  {
    id: "KB-POWER-INTEREST",
    title: "权力利益方格",
    kind: "tool",
    domain: "项目干系人管理",
    definition: "根据权力和利益两个维度，将干系人分为重点管理、令其满意、随时告知和监督四类。",
    plainLanguage: "用两个问题决定管理精力：他能多大程度影响项目？他对项目结果有多关心？",
    timing: "识别和分析干系人时使用，重大变化后重新评估。",
    inputs: ["干系人信息", "影响力判断", "利益判断"],
    tools: ["权力评分", "利益评分", "四象限分类"],
    outputs: ["重点管理", "令其满意", "随时告知", "监督"],
    related: ["KB-IDENTIFY-STAKEHOLDERS", "KB-STAKEHOLDER-REGISTER", "KB-ENGAGEMENT-MATRIX"],
    source: "《信息系统项目管理师教程（第4版）》· 权力利益方格",
    casePage: "stakeholder",
  },
  {
    id: "KB-ENGAGEMENT-MATRIX",
    title: "干系人参与度评估矩阵",
    kind: "tool",
    domain: "项目干系人管理",
    definition: "显示个体干系人当前参与程度和期望参与程度之间差距的矩阵。",
    plainLanguage: "找出谁还不了解、抵制或参与不足，并据此设计沟通和参与措施。",
    timing: "规划和监督干系人参与时使用，参与状态变化后更新。",
    inputs: ["干系人登记册", "当前参与程度", "期望参与程度"],
    tools: ["不了解", "抵制", "中立", "支持", "领导"],
    outputs: ["参与差距", "沟通与参与行动"],
    related: ["KB-STAKEHOLDER-REGISTER", "KB-POWER-INTEREST", "KB-IDENTIFY-STAKEHOLDERS"],
    source: "《信息系统项目管理师教程（第4版）》· 干系人参与度评估矩阵",
    casePage: "stakeholder",
  },
  {
    id: "KB-IDENTIFY-RISKS",
    title: "识别风险",
    kind: "process",
    domain: "项目风险管理",
    processGroup: "规划过程组",
    definition: "识别单个项目风险以及整体项目风险的来源并记录风险特征的过程。",
    plainLanguage: "系统地找出可能影响目标的威胁与机会，并说明原因、事件和后果。",
    timing: "在整个项目期间开展。",
    inputs: ["项目管理计划", "项目文件", "协议", "采购文档"],
    tools: ["专家判断", "数据收集", "数据分析", "人际与团队技能", "提示清单", "会议"],
    outputs: ["风险登记册", "风险报告", "项目文件更新"],
    related: ["KB-RISK-REGISTER", "KB-PROBABILITY-IMPACT", "KB-PROJECT-CHARTER"],
    source: "《信息系统项目管理师教程（第4版）》· 识别风险",
    casePage: "risk",
  },
  {
    id: "KB-RISK-REGISTER",
    title: "风险登记册",
    kind: "artifact",
    domain: "项目风险管理",
    definition: "列明已识别风险，并随着分析和应对规划持续记录责任人、策略、行动、触发条件、应急计划和剩余风险等信息。",
    plainLanguage: "它不是一次性清单，而是一份从识别到应对、监督都持续演进的项目文件。",
    timing: "识别风险时创建，后续风险分析、应对规划、实施和监督过程中持续更新。",
    inputs: ["风险来源", "假设日志", "干系人登记册", "项目基准"],
    tools: ["风险分类", "概率影响评估", "应对策略"],
    outputs: ["风险清单", "责任人", "分析结果", "应对和监督信息"],
    related: ["KB-IDENTIFY-RISKS", "KB-PROBABILITY-IMPACT", "KB-ASSUMPTION-LOG"],
    source: "《信息系统项目管理师教程（第4版）》· 风险登记册",
    casePage: "risk",
  },
  {
    id: "KB-PROBABILITY-IMPACT",
    title: "概率和影响矩阵",
    kind: "tool",
    domain: "项目风险管理",
    definition: "把风险发生概率与对项目目标的影响组合起来，支持风险优先级排序。",
    plainLanguage: "把风险放入同一尺度，帮助团队先处理真正重要的不确定性。",
    timing: "实施定性风险分析时使用，并可在风险监督时重新评估。",
    inputs: ["风险登记册", "概率定义", "影响定义"],
    tools: ["概率评分", "影响评分", "阈值与兜底规则"],
    outputs: ["风险等级", "优先级", "进一步分析名单"],
    related: ["KB-RISK-REGISTER", "KB-IDENTIFY-RISKS", "KB-PG-MC"],
    source: "《信息系统项目管理师教程（第4版）》· 概率和影响矩阵",
    casePage: "risk",
  },
  {
    id: "KB-PROJECT-MANAGEMENT-PLAN",
    title: "项目管理计划",
    kind: "artifact",
    domain: "项目整合管理",
    definition: "说明项目将如何执行、监督、控制和收尾，整合各知识领域管理计划和项目基准。",
    plainLanguage: "这是管理项目的总说明书，包含各项子计划和批准的范围、进度、成本基准。",
    timing: "规划阶段形成，在项目期间通过正式变更控制更新。",
    inputs: ["项目章程", "其他过程输出", "事业环境因素", "组织过程资产"],
    tools: ["专家判断", "数据收集", "会议"],
    outputs: ["子管理计划", "项目基准", "生命周期与开发方法"],
    related: ["KB-PG-PLAN", "KB-INTEGRATED-CHANGE", "KB-PROJECT-CHARTER"],
    source: "《信息系统项目管理师教程（第4版）》· 制定项目管理计划",
    casePage: "overview",
  },
  {
    id: "KB-INTEGRATED-CHANGE",
    title: "实施整体变更控制",
    kind: "process",
    domain: "项目整合管理",
    processGroup: "监控过程组",
    definition: "审查所有变更请求，批准变更，管理对可交付成果、项目文件和项目管理计划的变更，并沟通处理结果。",
    plainLanguage: "不让项目在不知不觉中改变：先评估影响，再由有权人员决定，最后同步计划和文件。",
    timing: "从项目开始持续到项目结束。",
    inputs: ["项目管理计划", "项目文件", "工作绩效报告", "变更请求"],
    tools: ["专家判断", "变更控制工具", "数据分析", "决策", "会议"],
    outputs: ["批准的变更请求", "项目管理计划更新", "项目文件更新"],
    related: ["KB-PG-MC", "KB-PROJECT-MANAGEMENT-PLAN", "KB-RISK-REGISTER"],
    source: "《信息系统项目管理师教程（第4版）》· 实施整体变更控制",
    casePage: "overview",
  },
  {
    id: "KB-CLOSE",
    title: "结束项目或阶段",
    kind: "process",
    domain: "项目整合管理",
    processGroup: "收尾过程组",
    definition: "终结项目、阶段或合同的所有活动，正式完成项目工作。",
    plainLanguage: "把验收、移交、合同、财务、文档和经验教训一起收干净。",
    timing: "项目、阶段或合同结束时开展。",
    inputs: ["项目章程", "项目管理计划", "项目文件", "验收的可交付成果"],
    tools: ["专家判断", "数据分析", "会议"],
    outputs: ["最终成果移交", "最终报告", "组织过程资产更新"],
    related: ["KB-PG-CLOSE", "KB-LIFECYCLE", "KB-PROJECT-MANAGEMENT-PLAN"],
    source: "《信息系统项目管理师教程（第4版）》· 结束项目或阶段",
    casePage: "overview",
  },
];

export const knowledgeEdges = [
  ["KB-LIFECYCLE", "KB-PROCESS-GROUPS", "组织管理节奏"],
  ["KB-PROCESS-GROUPS", "KB-PG-INIT", "包含"],
  ["KB-PROCESS-GROUPS", "KB-PG-PLAN", "包含"],
  ["KB-PROCESS-GROUPS", "KB-PG-EXEC", "包含"],
  ["KB-PROCESS-GROUPS", "KB-PG-MC", "包含"],
  ["KB-PROCESS-GROUPS", "KB-PG-CLOSE", "包含"],
  ["KB-PG-INIT", "KB-CHARTER-PROCESS", "包含过程"],
  ["KB-CHARTER-PROCESS", "KB-PROJECT-CHARTER", "输出·创建"],
  ["KB-CHARTER-PROCESS", "KB-ASSUMPTION-LOG", "输出·创建"],
  ["KB-PROJECT-CHARTER", "KB-IDENTIFY-STAKEHOLDERS", "输入"],
  ["KB-IDENTIFY-STAKEHOLDERS", "KB-STAKEHOLDER-REGISTER", "输出·创建/更新"],
  ["KB-POWER-INTEREST", "KB-IDENTIFY-STAKEHOLDERS", "工具"],
  ["KB-STAKEHOLDER-REGISTER", "KB-ENGAGEMENT-MATRIX", "输入"],
  ["KB-PROJECT-CHARTER", "KB-IDENTIFY-RISKS", "输入"],
  ["KB-ASSUMPTION-LOG", "KB-IDENTIFY-RISKS", "输入"],
  ["KB-STAKEHOLDER-REGISTER", "KB-IDENTIFY-RISKS", "输入"],
  ["KB-IDENTIFY-RISKS", "KB-RISK-REGISTER", "输出·创建/更新"],
  ["KB-RISK-REGISTER", "KB-PROBABILITY-IMPACT", "输入"],
  ["KB-PG-PLAN", "KB-PROJECT-MANAGEMENT-PLAN", "形成"],
  ["KB-PROJECT-MANAGEMENT-PLAN", "KB-INTEGRATED-CHANGE", "输入/更新"],
  ["KB-PG-MC", "KB-INTEGRATED-CHANGE", "包含过程"],
  ["KB-PG-CLOSE", "KB-CLOSE", "包含过程"],
] as const;

export const lifecyclePhases = [
  { id: "concept", title: "启动", subtitle: "确认价值与可行性" },
  { id: "prepare", title: "规划", subtitle: "授权、计划与基线" },
  { id: "build", title: "执行", subtitle: "完成工作与迭代集成" },
  { id: "deploy", title: "监控", subtitle: "验收、灰度与上线" },
  { id: "close", title: "收尾", subtitle: "移交、归档与复盘" },
] as const;

export const lifecycleActivities = [
  { id: "integration", title: "整合", phases: [1, 2, 3, 4, 5], knowledgeId: "KB-MA-INTEGRATION" },
  { id: "stakeholder", title: "干系人", phases: [1, 2, 3, 4], knowledgeId: "KB-MA-STAKEHOLDER" },
  { id: "scope", title: "范围", phases: [1, 2, 3, 4, 5], halfStart: true, knowledgeId: "KB-MA-SCOPE" },
  { id: "schedule", title: "进度", phases: [2, 4], knowledgeId: "KB-MA-SCHEDULE" },
  { id: "cost", title: "成本", phases: [2, 4], knowledgeId: "KB-MA-COST" },
  { id: "quality", title: "质量", phases: [2, 3, 4], knowledgeId: "KB-MA-QUALITY" },
  { id: "communication", title: "沟通", phases: [2, 3, 4], knowledgeId: "KB-MA-COMMUNICATION" },
  { id: "risk", title: "风险", phases: [2, 3, 4], knowledgeId: "KB-MA-RISK" },
  { id: "procurement", title: "采购", phases: [2, 3, 4, 5], knowledgeId: "KB-MA-PROCUREMENT" },
  { id: "resource", title: "资源", phases: [2, 3, 4, 5], halfEnd: true, knowledgeId: "KB-MA-RESOURCE" },
] as const;

type ProcessCell = { state: "primary" | "continuous" | "gate" | "none"; label: string };

export const processGroupLanes: Array<{
  id: string;
  title: string;
  knowledgeId: string;
  cells: ProcessCell[];
}> = [
  { id: "init", title: "启动过程组", knowledgeId: "KB-PG-INIT", cells: [
    { state: "primary", label: "主要" }, { state: "gate", label: "阶段启动" }, { state: "gate", label: "阶段启动" }, { state: "gate", label: "阶段启动" }, { state: "none", label: "—" },
  ] },
  { id: "plan", title: "规划过程组", knowledgeId: "KB-PG-PLAN", cells: [
    { state: "continuous", label: "初步" }, { state: "primary", label: "主要" }, { state: "continuous", label: "滚动规划" }, { state: "continuous", label: "发布规划" }, { state: "gate", label: "收尾计划" },
  ] },
  { id: "exec", title: "执行过程组", knowledgeId: "KB-PG-EXEC", cells: [
    { state: "none", label: "—" }, { state: "continuous", label: "组建团队" }, { state: "primary", label: "主要" }, { state: "primary", label: "交付部署" }, { state: "gate", label: "移交" },
  ] },
  { id: "mc", title: "监控过程组", knowledgeId: "KB-PG-MC", cells: [
    { state: "gate", label: "立项检查" }, { state: "continuous", label: "基准检查" }, { state: "primary", label: "持续" }, { state: "primary", label: "持续" }, { state: "continuous", label: "最终核对" },
  ] },
  { id: "close", title: "收尾过程组", knowledgeId: "KB-PG-CLOSE", cells: [
    { state: "none", label: "—" }, { state: "gate", label: "阶段收尾" }, { state: "gate", label: "阶段收尾" }, { state: "continuous", label: "验收关闭" }, { state: "primary", label: "主要" },
  ] },
];

export type DocumentTouch = "input" | "create" | "update";

export const documentActivities = [
  { id: "A02", title: "制定项目章程", stage: "概念与立项", group: "启动", knowledgeId: "KB-CHARTER-PROCESS" },
  { id: "A03", title: "识别干系人", stage: "组织与准备", group: "启动", knowledgeId: "KB-IDENTIFY-STAKEHOLDERS" },
  { id: "A04", title: "制定项目管理计划", stage: "组织与准备", group: "规划", knowledgeId: "KB-PROJECT-MANAGEMENT-PLAN" },
  { id: "A05", title: "规划范围与基准", stage: "组织与准备", group: "规划", knowledgeId: "KB-PG-PLAN" },
  { id: "A06", title: "识别风险", stage: "组织与准备", group: "规划", knowledgeId: "KB-IDENTIFY-RISKS" },
  { id: "A07", title: "规划风险应对", stage: "组织与准备", group: "规划", knowledgeId: "KB-RISK-REGISTER" },
  { id: "A08", title: "指导与管理项目工作", stage: "建设与交付", group: "执行", knowledgeId: "KB-PG-EXEC" },
  { id: "A09", title: "管理干系人参与", stage: "建设与交付", group: "执行", knowledgeId: "KB-ENGAGEMENT-MATRIX" },
  { id: "A10", title: "监控项目工作", stage: "建设与交付", group: "监控", knowledgeId: "KB-PG-MC" },
  { id: "A11", title: "实施整体变更控制", stage: "建设与交付", group: "监控", knowledgeId: "KB-INTEGRATED-CHANGE" },
  { id: "A12", title: "监督风险", stage: "验证与部署", group: "监控", knowledgeId: "KB-RISK-REGISTER" },
  { id: "A13", title: "结束项目或阶段", stage: "移交与结束", group: "收尾", knowledgeId: "KB-CLOSE" },
] as const;

export const projectDocuments = obsidianProjectDocuments.map((document) => ({
  id: document.id,
  title: document.title,
  category: "32项目文件",
  knowledgeId: `document:${document.id}`,
}));
