export type EngagementLevel = "unaware" | "resistant" | "neutral" | "supportive" | "leading";

export type Stakeholder = {
  id: string;
  role: string;
  organization: string;
  internalExternal: "内部" | "外部";
  needs: string;
  influence: string;
  power: number;
  interest: number;
  attitude: "支持" | "中立" | "抵制";
  currentEngagement: EngagementLevel;
  desiredEngagement: EngagementLevel;
  strategy: string;
  sourceIds: string[];
};

export const engagementLevels: Array<{ id: EngagementLevel; label: string }> = [
  { id: "unaware", label: "不了解" },
  { id: "resistant", label: "抵制" },
  { id: "neutral", label: "中立" },
  { id: "supportive", label: "支持" },
  { id: "leading", label: "领导" },
];

export const initialStakeholders: Stakeholder[] = [
  {
    id: "STK-001",
    role: "项目发起人",
    organization: "市住建部门",
    internalExternal: "外部",
    needs: "在批准预算和期限内提升规划报建效率，形成可持续运营的数字审查能力。",
    influence: "批准章程、资金和关键范围变更，协调跨部门政策与业务资源。",
    power: 5,
    interest: 5,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；在规则基线、试点、重大风险和验收阶段直接参与决策。",
    sourceIds: ["OPEN-002", "project-charter.sponsor"],
  },
  {
    id: "STK-002",
    role: "项目经理",
    organization: "承建方项目管理办公室",
    internalExternal: "内部",
    needs: "获得正式授权、稳定的跨专业资源和清晰的双方升级机制。",
    influence: "整合计划、协调资源、管理风险和变更，推动管理成果形成。",
    power: 5,
    interest: 5,
    attitude: "支持",
    currentEngagement: "leading",
    desiredEngagement: "leading",
    strategy: "重点管理；维护整体路径、决策日志、接口清单和项目管理计划。",
    sourceIds: ["OPEN-002", "project-charter.project_manager"],
  },
  {
    id: "STK-003",
    role: "规划审查业务负责人",
    organization: "住建部门审查业务处室",
    internalExternal: "外部",
    needs: "审查流程符合现行业务，规则口径清晰，意见、依据和结论能够完整追溯。",
    influence: "决定业务流程、审查口径、规则优先级和最终验收结论。",
    power: 5,
    interest: 5,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；主持业务规则确认、场景验收和真实项目试点复盘。",
    sourceIds: ["INT-002", "INT-006", "F-COMPLIANCE"],
  },
  {
    id: "STK-004",
    role: "产品与需求负责人",
    organization: "承建方数字产品部",
    internalExternal: "内部",
    needs: "把报建审查流程拆成可验证能力，维持产品范围与业务目标一致。",
    influence: "决定需求优先级、迭代验收和试点反馈的产品闭环。",
    power: 4,
    interest: 5,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；负责产品目标、需求跟踪矩阵和业务验证闭环。",
    sourceIds: ["INT-003", "INT-009", "J-ITERATION"],
  },
  {
    id: "STK-005",
    role: "BIM 技术负责人",
    organization: "BIM 平台技术组",
    internalExternal: "内部",
    needs: "模型交付标准、规整规则、构件语义和轻量化性能基线明确。",
    influence: "决定模型兼容范围、数据质量方案和 BIM 技术边界。",
    power: 4,
    interest: 5,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；共同维护模型标准、测试样本库和性能基线。",
    sourceIds: ["F-MODEL-DATA", "RISK-003", "RISK-005"],
  },
  {
    id: "STK-006",
    role: "智能审查引擎负责人",
    organization: "算法与规则引擎组",
    internalExternal: "内部",
    needs: "规则定义、专家标注样本、准确率口径和性能目标保持稳定。",
    influence: "影响自动审查准确率、规则覆盖率和核心技术验收。",
    power: 4,
    interest: 5,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；对规则版本、测试数据和准确率证据负责。",
    sourceIds: ["INT-009", "F-COMPLIANCE", "RISK-001"],
  },
  {
    id: "STK-007",
    role: "信息安全负责人",
    organization: "信息安全与运维部",
    internalExternal: "内部",
    needs: "报建材料和 BIM 模型具备分级授权、加密、审计、备份和安全测试证据。",
    influence: "可阻止不满足安全门槛的平台进入试点或正式验收。",
    power: 5,
    interest: 5,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；前置参与安全架构和权限模型评审并负责安全阶段门。",
    sourceIds: ["J-GOVERNANCE", "RISK-002", "RISK-008"],
  },
  {
    id: "STK-008",
    role: "规划法规专家",
    organization: "建筑标准与规划专家组",
    internalExternal: "外部",
    needs: "条文解释、例外条件、版本生效范围和机器规则表达保持一致。",
    influence: "可要求调整规则库和审查结论，是智能审查可信度的关键把关人。",
    power: 5,
    interest: 4,
    attitude: "中立",
    currentEngagement: "neutral",
    desiredEngagement: "leading",
    strategy: "重点管理；建立专家复核与规则签发机制，以证据推动其从中立转为领导。",
    sourceIds: ["F-COMPLIANCE", "J-GOVERNANCE", "RISK-001", "RISK-006"],
  },
  {
    id: "STK-009",
    role: "设计院代表",
    organization: "首批试点设计院",
    internalExternal: "外部",
    needs: "模型交付标准清晰、上传反馈可理解、修改意见定位准确且闭环高效。",
    influence: "其模型质量和使用反馈影响兼容范围、产品体验和试点成效。",
    power: 3,
    interest: 5,
    attitude: "中立",
    currentEngagement: "neutral",
    desiredEngagement: "supportive",
    strategy: "随时告知；通过模型规整培训、试点共创和问题闭环持续参与。",
    sourceIds: ["F-MODEL-DATA", "RISK-003", "A-PILOT"],
  },
  {
    id: "STK-010",
    role: "测试与质量负责人",
    organization: "质量保障部",
    internalExternal: "内部",
    needs: "获得模型格式、建筑类型、规则场景、性能和安全用例覆盖基线。",
    influence: "影响质量门槛、试点准入和验收风险是否可接受。",
    power: 4,
    interest: 4,
    attitude: "支持",
    currentEngagement: "supportive",
    desiredEngagement: "leading",
    strategy: "重点管理；维护端到端测试门禁、规则回归集和验收证据包。",
    sourceIds: ["INT-009", "RISK-005", "RISK-006"],
  },
  {
    id: "STK-011",
    role: "BIM 引擎供应商",
    organization: "第三方技术服务商",
    internalExternal: "外部",
    needs: "接口范围、模型规模、版本计划、性能验收和责任边界清晰。",
    influence: "引擎质量和交付时间可能影响核心能力集成与项目验收。",
    power: 3,
    interest: 3,
    attitude: "中立",
    currentEngagement: "neutral",
    desiredEngagement: "supportive",
    strategy: "保持沟通；通过合同里程碑、性能样本和联合集成计划降低依赖。",
    sourceIds: ["RISK-004", "RISK-005"],
  },
  {
    id: "STK-012",
    role: "外部政务平台负责人",
    organization: "控规库与政务数据平台",
    internalExternal: "外部",
    needs: "接口申请、数据字段、安全责任和联调窗口符合平台规范。",
    influence: "可影响外部数据接入和联调进度，但对本项目具体产品目标兴趣较低。",
    power: 4,
    interest: 2,
    attitude: "中立",
    currentEngagement: "unaware",
    desiredEngagement: "neutral",
    strategy: "令其满意；尽早完成接口申请、字段确认和测试环境排期。",
    sourceIds: ["F-INTEGRATION", "RISK-007"],
  },
];
